### ISSUE TITLE
'gcloud auth list' inside a build step reports the wrong service account

### ISSUE THREAD

**Issue by skelterjohn** [GoogleCloudPlatform/container-builder-local#28]
It should be my user account, but it is the builder service account (which is not actually being used).

    $ cat cb.yaml 
    steps:
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['auth', 'list']
    $ container-builder-local --config cb.yaml --dryrun=false .2017/08/22 16:38:48 Warning: The server docker version installed (1.12.6) is different from the one used in GCB (17.05-ce)
    2017/08/22 16:38:48 Warning: The client docker version installed (1.12.6) is different from the one used in GCB (17.05-ce)
    370e1a589c8c317dfde376d78c211088068672ddfcf621b4ab7b50f7447d77d8
    2017/08/22 16:38:50 [docker run -d -p=8082:80 --name=metadata gcr.io/cloud-builders/metadata]
    2017/08/22 16:38:51 [docker network connect --alias=metadata --alias=metadata.google.internal --ip=169.254.169.254 cloudbuild metadata]
    2017/08/22 16:38:51 Started spoofed metadata server
    2017/08/22 16:38:52 status changed to "BUILD"
    BUILD
    Already have image (with digest): gcr.io/cloud-builders/gcloud
    To set the active account, run:
    Credentialed Accounts:
     - <redacted>@cloudbuild.gserviceaccount.com ACTIVE
        $ gcloud config set account `ACCOUNT`
    
    2017/08/22 16:38:53 status changed to "DONE"
    DONE

**Comment by bendory** [comment]
I just merged a fix for this into the master branch. #30 
If you check out and build this repo, this issue will be resolved. Will post here once we have released the fix via cloud-SDK.

**Comment by bendory** [comment]
v0.2.2 will fix this problem; expect a release in the coming 1-2 weeks

**Comment by bendory** [comment]
If you `gcloud components update` to version 170.0.0 or later, this issue is resolved.
