### ISSUE TITLE
Feature request: direct source mounting 

### ISSUE THREAD

**Issue by kubaj** [GoogleCloudPlatform/container-builder-local#33]
The current implementation creates docker volume and copies source code to the created volume. Build process is running on top of that volumes so changes are not written back to the source code. 

Would be possible to add a switch that allows mounting of a source code directly to a build step container so changes that will be made in the build step will be written back to the source code? I'd like to have build pipeline same on the cloud builder and locally and I also want to keep some generated code in the source (gitignored) due to IDE syntax highlighting.

Thank you

**Comment by Philmod** [comment]
Hey @kubaj, we decided to use a volume not to modify the code on your machine. This decision was made on purpose.

When you use the Google Container Builder service, how do you transfer the transformed code to your machine? You could use the same technique (maybe copying files to GCS in the build, then copying back from GCS to your machine).

**Comment by skelterjohn** [comment]
Another trick is to have a step that volume-mounts something from your disk.

    - name: 'gcr.io/cloud-builders/docker'
      args: 
      - 'run'
      - '--volume=/path/to/local/directory:/export'
      - '--entrypoint=bash'
      - 'ubuntu'
      - '-c'
      - |
        cp files_in_workspace /export

**Comment by kubaj** [comment]
@Philmod, now I'm not transferring code back to my machine. What I want to achieve is to have one cloudbuilder.yaml that can be used for local builds and also for GCB builds. Building works fine, but one build step is building protocol buffers to Go code - I want to have this Go code written back to the source due to intellisense in IDE.

@skelterjohn this should be working as a fix but this step will fail on GCB

Would be possible that this feature would be merged into the upstream if I create PR?

**Comment by skelterjohn** [comment]
Perhaps a `--persist-workspace` (or perhaps a better name) flag that volume-mounts your host directory into `/workspace` rather than copying the contents into a volume first? I think this would have high value for testing.

**Comment by Philmod** [comment]
@kubaj After some discussion with the team, we prefer to mount the volume to your host directory, it is too "dangerous" to modify your initial code.
But what do you think about persisting the volume that contains the workspace? Using a flag like `--persist-workspace-volume`?

**Comment by gelidus** [comment]
@Philmod this would mean overwriting the whole project after build or knowing where the generated files are to copy them, right? May I ask why you consider this as being dangerous?

**Comment by Philmod** [comment]
We would *not* overwrite the host files. We don't want to mount the host directory, because that could be surprising for the user to see her files modified.

By leaving the volume with modified files, the user could then copy the files wherever she wants.

Does that make sense?

cc @javier-b-perez

**Comment by eug48** [comment]
Not overwriting the host workspace sounds good to me - it makes builds more reproducible.

More generally, persistent volumes would also be useful for things like maintaining npm caches across rebuilds. So maybe consider per-volume opt-in,
e.g. `--persist-volume workspace --persist-volume npm-cache` ?

**Comment by javier-b-perez** [comment]
For the use case I documented in https://github.com/GoogleCloudPlatform/container-builder-local/issues/34 I don't think I need the volume. A volume will partially solve my issue.

I just need "something" that copy the files from inside the volume to a local path.
like:
steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "hello" > hello.txt

artifacts:
  - path: '/tmp/local_dir'
    files: '*.txt'

If you provide the persist volume I will need to run another docker and then cp the files from the volume to the local host.

**Comment by kubaj** [comment]
I can't really understand why is this considered dangerous. Builder will in default work as is working now. You'd need a special switch (with caution notice in manual) to use mount instead of the volume. In this way, for example, we should also remove `--force` from git because it can make surprising behavior.

Having volume that persists after build is nice but it's not very suitable for my use case because I'd have to keep a list of files that I need to copy from volume to my source after the build.

**Comment by Philmod** [comment]
The local builder should be almost-idempotent: it can be ran many times on the same source and should give the same output. If the local builder is linked to the host source files, they may be mutated and break the idempotence; this is what I meant by "dangerous".

If the `--persist-volume` flag doesn't work for you, we will look into another solution, but it might take more time.

**Comment by Philmod** [comment]
What do you think about a flag that would copy all the workspace into a defined host path? `--write-workspace=<path-to-host-dir>`

I'm thinking about limiting the path to `/tmp/*` to avoid any problem. Would that work for you?

**Comment by javier-b-perez** [comment]
--write-workspace could work for me.
I'm interested on a subset of the files in the workspace, but this will be a good start.

**Comment by Philmod** [comment]
@javier-b-perez We are working on a broader solution, but I figured y'all might need a solution now.

**Comment by Philmod** [comment]
The `--write-workspace` flag is now available.
