### ISSUE TITLE
Feature request: Release build artifacts to local directory.

### ISSUE THREAD

**Issue by javier-b-perez** [GoogleCloudPlatform/container-builder-local#34]
As a user of the container-builder-local I would like to be able to "push" build artifacts (not just images) from the workspace into a local directory. 
I want to specify with a regex the files that I want to get from the workspace into a specified local directory.
This will be executed at the end of the workflow and only in local mode. If I run the build on Google Cloud Container Builder, I want to store the files on Google Cloud Storage buckets.

Related to https://github.com/GoogleCloudPlatform/container-builder-local/issues/33

**Comment by Philmod** [comment]
Hey @javier-b-perez, this would be part of a bigger feature for GCB. I'll keep you updated.
In the meantime, I'm planning to add a flag to the local builder, see #33

**Comment by Philmod** [comment]
The `--write-workspace` flag is now available.
