### ISSUE TITLE
[RFC] Injecting substitutions provided by the GCP Container Builder

### ISSUE THREAD

**Issue by Sinjo** [GoogleCloudPlatform/container-builder-local#43]
# Problem

Currently, there's a feature gap when trying to run your builds locally. A number of substitutions are [provided automatically](https://cloud.google.com/container-builder/docs/configuring-builds/substitute-variable-values) when using the real GCP Container Builder. As it stands, there's no way to provide them locally.

The cause of the issue is the [validation regex](https://github.com/GoogleCloudPlatform/container-builder-local/blob/6dff520b05094995bdea2cc4feb279fb1da03127/validate/validate.go#L59) for user-defined substitutions enforces an underscore at the start of the variable name.

This means that once you're using the automatically provided substitutions, you probably can't build locally any more.

# Proposals

These are some options I've thought of. There might be a better way though!

## 1. Relax the validation of substitution parameters to allow injection of the GCP automatic substitutions

As well as allowing substitution variables starting with `_`, we could allow the list of [built-in variables](https://github.com/GoogleCloudPlatform/container-builder-local/blob/6dff520b05094995bdea2cc4feb279fb1da03127/validate/validate.go#L60).

This seems like a pretty low-effort way to solve the problem, and I can't see any obvious downsides. I think keeping the `_` restriction in general is good, as removing it entirely would mislead people working locally.

## 2. Automatically set up the source provenance based on the current working directory

We could look for the `.git` folder in your current working directory and use it to determine the values of the substitutions the GCP builder would provide.

This could either be fully automatic or behind a flag. Fully automatic might be a little bit too magic and cause cause confusion for people for the sake of a minor convenience.

A disadvantage of this approach is that there are more VCSs than git, and we'd need to implement separate code for each one that's supported by GCP.

## 3. Add extra flags to set up the source provenance

Rather than inferring the source provenance values automatically, we could add flags for each of them.

This feels like a worse version of option 1. It has an advantage over option 2 though - no VCS-specific code.

# Next steps

It'd be good to get some feedback and hopefully settle on an approach.

Depending on how deeply the changes run through the codebase, I'd be happy to help out with the implementation. If it's going to be quite involved, I might be more of a hinderance!

Getting a fix in for this would make it possible to simulate the GCP environment more closely. On the project I'm working on, it would make local builds possible again.

**Comment by Philmod** [comment]
Hey Sinjo,

We are in the process of relaxing the substitutions you can pass along, which now includes built-in substitutions. This feature is already available with `gcloud container builds submit`, and will be soon added here.

**Comment by Sinjo** [comment]
Oh, great news! Looking forward to the next release.

**Comment by rbq** [comment]
When will this be out, roughly?

**Comment by Philmod** [comment]
@rbq Soon, before the end of the quarter.

cc @codrienne

**Comment by norrs** [comment]
Suggest method 1, also what I did as a work-around fix in https://gist.github.com/norrs/34f25e6dd02cf5f7805d925f2663ab46 with "inline editing" of the config file using a wrapper script.

I guess we can just close https://github.com/GoogleCloudPlatform/container-builder-local/issues/44 as this one describes the issue. Sorry for opening the duplicate.

**Comment by codrienne** [comment]
Our latest release permits overriding substitutions  in localbuilder using the --substitutions flag, including built-in substitutions (REPO_NAME, BRANCH_NAME, TAG_NAME, REVISION_ID, COMMIT_SHA, SHORT_SHA).

This will be available in container-builder-local in the next Cloud SDK release, May 1. Once the SDK release goes out, update your gcloud and it should work. In the meantime, the source code is available in the repo. Sorry for the delay.

Closing the issue.
