### ISSUE TITLE
Not able to provide substitution for global substitutions 

### ISSUE THREAD

**Issue by norrs** [GoogleCloudPlatform/container-builder-local#44]
I guess the whole idea about `container-builder-local` is that you are supposed to be able to test and iterate on your `cloudbuild.yaml` files before submitting and running em in the cloud.

Since the hosted GCP container builder service provides global substitutions (example COMMIT_SHA), this `container-builder-local` tool should allow you to set this, but currently the validator in https://github.com/GoogleCloudPlatform/container-builder-local/blob/master/validate/validate.go#L152 is stopping you.

I guess this maybe has been intended seen from Google's perspective to protect the runtime environment from external sources to change these global provided substitutions, as you support user submitted substitutions if it starts with `_`. This doesn't help us when testing locally when we want to use an global substitution in our `cloudbuild.yaml`.   

**Suggested fix**: the tool should allow to set these global substitutions , and you move this validating code into your proprietary GCE container-builder.

As a **work around** I ended up with using https://gist.github.com/norrs/34f25e6dd02cf5f7805d925f2663ab46 for now.

**Comment by Philmod** [comment]
We have a fix for this, @codrienne will release it sometimes this week.

**Comment by norrs** [comment]
Closing this one as it is a duplicate. Sorry about that, I should have noticed.
