### ISSUE TITLE
$BUILD_ID is always empty

### ISSUE THREAD

**Issue by christian-roggia** [GoogleCloudPlatform/container-builder-local#45]
While buildConfig.ProjectId (aka PROJECT_ID) is populated with the expected value https://github.com/GoogleCloudPlatform/container-builder-local/blob/master/localbuilder_main.go#L162 buildConfig.Id (aka BUILD_ID) is never populated and is left empty.

This unexpected behavior results in breaking changes of the building pipeline and can result in the failure of the building process.

BUILD_ID should be generated randomly for each building process to emulate the expected behavior of the container builder.

**Comment by christian-roggia** [comment]
This issue is related to https://github.com/GoogleCloudPlatform/container-builder-local/issues/43 but takes into analysis the **default behavior** of BUILD_ID inside the local cloud builder.

**Comment by codrienne** [comment]
The latest release to the repo sets the build id to 

    "localbuild_" + uuid.New()

for local builds. 

You can see the id assigned [here](https://github.com/GoogleCloudPlatform/container-builder-local/blob/master/localbuilder_main.go#L150), and printed [here](https://github.com/GoogleCloudPlatform/container-builder-local/blob/master/build/build.go#L226) when the build starts.

**Comment by codrienne** [comment]
It will be available in container-builder-local in the next Cloud SDK release (May 1). After you update your gcloud it should work :)
